### ISSUE TITLE
Setup Python unit-testing framework

### ISSUE THREAD

**Issue by benpankow** [illinois/clickin#27]
We need to figure out how we want to structure our Python unit tests, and which framework we should use. [unittest](https://docs.python.org/3/library/unittest.html) is part of the Python standard library, but is more barebones. [pytest](https://docs.pytest.org/en/latest/) and [nose](https://nose.readthedocs.io/en/latest/) are some popular alternatives which are a bit more full-featured.

**Comment by m-pitera** [comment]
I've only worked with pytest so I may be biased, but I think that we should use pytest with it being more fully featured and preferred over nose due to more extensive documentation. It also looks nicer imo, with the way it outputs false assertions 😎

**Comment by m-pitera** [comment]
I wrote some tests for #30 in pytest. At the moment the file is in the same folder as the backend, but once we decide on this we can move the test files into their own folder if we decide that's necessary
