### ISSUE TITLE
Short URL Redirection System

### ISSUE THREAD

**Issue by sathreddy** [illinois/clickin#31]
Related to #30 .

Given a short URL (e.g. join.click.in/xYz6), it should route user to target polling session page and authenticate if previously logged in.

**Comment by m-pitera** [comment]
I would like to tackle this, but I have no idea where to start.

A few questions:

1. What do you mean by target polling session page? Would that be the remote screen?
2. Would we need to store the user's data somewhere? Is this already happening?
