### ISSUE TITLE
Remote Component

### ISSUE THREAD

**Issue by sathreddy** [illinois/clickin#35]
Self-explanatory. Design wireframes as you're working so we can discuss UI.

Features:

1. 5 option buttons
2. Question Display
3. Transmission Confirmation
4. Text Input

**Comment by sathreddy** [comment]
Could perhaps be related to #33. Maybe we can have the same component but display different elements based on user roles? Thoughts @bstrauch24?

**Comment by brianstrauch** [comment]
@sathp I think this should look the same to everyone. What elements would change based on roles? This should just be the basic "clicker remote" view: the question, buttons, yes/no validation. In the future, we could handle arbitrary input, variable number of answers, etc.

**Comment by hyosang2** [comment]
Hi, can I be assigned to this issue?

Improvements: 

1. The ability for instructors to highlight certain words in the question for ease of students' understanding.
2. Ergonomics: Easy to use with one hand
3. Accessibility (Closer to general UX than UI but a possible feature): ex. haptic feedback
