### ISSUE TITLE
Linters for python and javascript

### ISSUE THREAD

**Issue by brianstrauch** [illinois/clickin#42]

**Comment by yuppers396** [comment]
Let's start with a discussion of what the repo's style conventions should be and which linting tools should be used (related to isssue #24).

There are general JavaScript style guides, such as the JavaScript Standard Style Guide used by many companies, as well as style guides from high-profile companies, such as AirBnB and Google (Medium Post: https://bre.is/3mGhKhfF).

I believe we should use Google's JavaScript style guide and ESLint to enforce it.  ESLint configuration exists to autoformat code in accordance with many of the above style guides, and setting this up for Google's style guide looks easy (ESLint configuration: https://github.com/google/eslint-config-google; Medium post on setting up ESLint: https://bre.is/YnLTB3Dz).  Also, having interned at Google twice before, I can attest to their commitment to maintaining a readable, organized codebase with their style guidelines.

**Comment by m-pitera** [comment]
That makes sense.

For Python i suggest we use Pylint as it uses the [PEP 8 Style guide](https://www.python.org/dev/peps/pep-0008/)

**Comment by m-pitera** [comment]
That makes sense.

How would we go about setting up a linter for python? I found pylint, but from what i can tell it's just something you use to test and run from the command line.

Would it be implemented in the same way as eslint as suggested in the medium article through putting it under pretest even though it's not a node module?

**Comment by benpankow** [comment]
There are a few options as to when the python linter could run - we could rely on people to run some sort of formatter like black locally and only check the linter on commit using Travis, or we could include linting as part of a python unit test which would run the linter and indicate a test failure if there are style issues.

**Comment by PradyumnaShome** [comment]
Linting as part of a test suite sounds like a good idea. @benpankow I think in both cases it would be simpler to integrate it with a test suite / as a yarn target.
