### ISSUE TITLE
Shibboleth Authentication

### ISSUE THREAD

**Issue by brianstrauch** [illinois/clickin#65]
Looks like we will need to contact someone from the school to get this set up. We need a URL similar to https://queue.illinois.edu/ which needs to be whitelisted by the school. Upon authentication, we will receive a parameter called `eppn` which I believe is the user's school email, i.e. `bts2@illinois.edu`

**Comment by sathreddy** [comment]
Why Shibboleth vs. a combination of Google OAuth and Azure AD?

**Comment by brianstrauch** [comment]
Queue and PrairieLearn both use it, and I think having a single form of sign in would be easier

**Comment by brianstrauch** [comment]
I'd be ok with starting out with Google OAuth, but I think it should support Shibboleth eventually

**Comment by sathreddy** [comment]
LGTM. Jk jk hope you’re doing well Brian.

Sent via Superhuman ***@***.***>


On Fri, Nov 10 2023 at 5:23 AM, Brian Strauch ***@***.******@***.***>> wrote:

Closed #65<https://github.com/illinois/clickin/issues/65> as completed.
